---
title: "Demos"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr) 
library(flextable)
library(officer)
```

## Ranking of tennis players

### Data 


```{r}
tennis_players <-
  data.frame(
    Rank = 1:10,
    Player = c(
      "Roger Federer", "Lleyton Hewitt", "Feliciano Lopez", "Ivo Karlovic", "Andy Murray",
      "Pete Sampras", "Greg Rusedski", "Tim Henman", "Novak Djokovic", "Andy Roddick"
    ),
    Percentage = c(92.63, 85.29, 89.86, 94.87, 88.89, 92.66, 90.33, 83.77, 89.12, 92.76),
    `Games Won` = c(2739L, 1740L, 1684L, 1645L, 1528L, 1478L, 1476L, 1461L, 1442L, 1410L),
    `Total Games` = c(2957L, 2040L, 1874L, 1734L, 1719L, 1595L, 1634L, 1744L, 1618L, 1520L),
    Matches = c(205L, 149L, 122L, 113L, 121L, 105L, 116L, 110L, 106L, 103L),
    head = c(
      "federer_head.png", "hewitt_head.png", "lopez_head.png", "karlovic_head.png",
      "murray_head.png", "sampras_head.png", "rusedski_head.png", "henman_head.png",
      "djokovic_head.png", "roddick_head.png"
    ),
    flag = c(
      "sui.png", "aus.png", "esp.png", "cro.png", "gbr.png", "usa.png",
      "gbr.png", "gbr.png", "srb.png", "usa.png"
    ),
    stringsAsFactors = FALSE
  ) %>%
  mutate(
    head = file.path("players", head),
    flag = file.path("flags", flag)
  )
tennis_players
```

## Mario kart

Souce: https://www.ardata.fr/en/flextable-gallery/2021-01-12-mario-kart/#data

### Data 

```{r}
mario_kart <- readxl::read_excel("Luigi_Fan2's Mario Kart 8 Deluxe Stat Chart.xlsx", range = "A2:M18")
mario_kart$image <- fs::dir_ls("mario", recurse = FALSE,
                               glob = "*.png") %>% 
    as.character()
mario_kart$star <- file.path("mario/star/Star_coin.png")
mario_kart$color <- "black"
mario_kart

fs::dir_tree("mario")
```

### flexcode

```{r}
set_flextable_defaults(font.family = "Arial", font.size = 9, padding = 2, digits = 1)

var_stat <- setdiff(names(mario_kart), c("image", "star", "color", "Characters"))

ft <- flextable(mario_kart, col_keys = c("Characters", var_stat)) %>% 
  set_header_labels(Land_speed = "Land", `Anti-G_speed` = "Anti-G", 
                    Water_speed = "Water", Gliding_speed = "Gliding") %>% 
  add_header_row(values = c("Characters", "Speed", "Accel", "Weight",
                            "Handling", "Traction", "M-turbo"),
                 colwidths = c(1, 4, 1, 1,
                               4, 1, 1)) %>%
    theme_box() %>% 
  merge_v(part = "header") %>%
    bold(part = "header") %>% 
  valign(valign = "center", part = "header") %>% 
  compose(j = "Characters", 
          value = as_paragraph(
            as_b(
              colorize(Characters, color = mario_kart$color)), 
            as_chunk(" ")
            ,as_image(image, width = 0.2, height = 0.2)
            
      )
  ) %>% 
  colformat_double(digits = 1) %>% 
  theme_zebra(odd_header = "#c7254e", even_header = "#c7254e",
              odd_body = "#fff5f5", even_body = "#f8f9fa") %>% 
  color(part = "header", color = "white") %>% 
  align(align = "right", part = "body") %>%
  rotate(rotation = "tbrl", part = "header") %>% 
  valign(valign = "bottom", part = "header") %>% 
  width(width = .55) %>% 
  width(j = 1, width = 1.3 ) %>% 
  autofit()
ft
```

```{r}
for(column in var_stat){
  i_selector <- as.formula(paste0("~`", column, "`>= max(`", column, "`, na.rm = TRUE)"))
  ft <- compose(ft, 
            i = i_selector, j = column, 
            value = as_paragraph(
              as_image(star, width = .15, height = .15), 
              as_chunk(" "), 
              as_chunk(.)), use_dot = TRUE
    )
}
ft <- ft %>% autofit() 

ft

flextable::save_as_pptx(ft, path = 'test.pptx')
flextable::save_as_html(ft, path = "html tables/mariokart_flextable_demo.html")
```

## Simple DEmo

```{r}
### ** Examples

img.file <- file.path( R.home("doc"),
  "html", "logo.jpg" )
if (require("magick")) {
  myft <- flextable( head(iris))
  myft <- compose( myft, i = 1:3, j = 1,
   value = as_paragraph(
     as_image(src = img.file),
     " ",
     as_chunk(Sepal.Length,
       props = fp_text_default(color = "red"))
   ),
   part = "body")
  ft <- autofit(myft)
  ft
}
```

## Table with density lines

```{r}
library(data.table)
z <- as.data.table(ggplot2::diamonds)
z <- z[, list(
  price = mean(price, na.rm = TRUE),
  list_col = list(.SD$x)
), by = "cut"]
z
```


```{r}
ft <- flextable(data = z) |>
  compose(j = "list_col", value = as_paragraph(
    plot_chunk(value = list_col, type = "dens", col = "pink", 
               width = 1.5, height = .4, free_scale = TRUE)
  )) |>
  colformat_double(big.mark = " ", suffix = " $") |> 
  set_header_labels(list_col = "density") |> 
  autofit()
ft
```
```{r}
library(data.table)
library(flextable)

z <- as.data.table(iris)
z <- z[ , list(
  Sepal.Length = mean(Sepal.Length, na.rm  = TRUE),
  z = list(.SD$Sepal.Length)
  ), by = "Species"]

ft <- flextable(z,
  col_keys = c("Species", "Sepal.Length", "box", "density"))
ft <- mk_par(ft, j = "box", value = as_paragraph(
  plot_chunk(value = z, type = "box",
             border = "red", col = "transparent")))
ft <- mk_par(ft, j = "density", value = as_paragraph(
 plot_chunk(value = z, type = "dens", col = "red")))
ft <- set_table_properties(ft, layout = "autofit", width = .6)
ft <- set_header_labels(ft, box = "boxplot", density= "density")
theme_vanilla(ft)
```
## Minibars

```{r}
ft <- flextable( head(iris, n = 10 ))

ft <- compose(ft, j = 1,
  value = as_paragraph(
    minibar(value = Sepal.Length, max = max(Sepal.Length))
  ),
  part = "body")

ft <- autofit(ft)
ft


```

